export default {
  products: [
    {
      _id: "1",
      name: "Canasta",
      category: "Home",
      image: "/images/canasta.jpg",
      price: 400,
      brand: "GGC",
      rating: 4.5,
      numReviews: 7,
    },
    {
      _id: "2",
      name: "Manta",
      category: "Parc",
      image: "/images/logo.png",
      price: 400,
      brand: "GGC",
      rating: 4.5,
      numReviews: 7,
    },
    {
      _id: "3",
      name: "Pote",
      category: "Home",
      image: "/images/canasta.jpg",
      price: 220,
      brand: "GGC",
      rating: 4.5,
      numReviews: 7,
    },
    {
      _id: "4",
      name: "Angie",
      category: "Home",
      image: "/images/canaste.jpeg",
      price: 550,
      brand: "GGC",
      rating: 4.5,
      numReviews: 4,
    },
    {
      _id: "5",
      name: "SSSSSST FFFFLEUR",
      category: "Home",
      image: "/images/panelimg.jpg",
      price: 20,
      brand: "GGC",
      rating: 1.5,
      numReviews: 9,
    },
    {
      _id: "6",
      name: "BUFANDA",
      category: "Parc",
      image: "/images/canasta.jpeg",
      price: 150,
      brand: "GGC",
      rating: 4.5,
      numReviews: 10,
    },
  ],
};
