export default {
  products: [
    {
      _id: "1",
      name: "Canasta",
      category: "Invierno",
      image: "/images/canasta.jpg",
      price: 400,
      brand: "GGC",
      rating: 4.5,
      numReviews: 7,
      description:
        "Canasta para vender, los mejores sin dudas, a precio barrato, te llega rapido a tu casa - devolución 30 días",
    },
    {
      _id: "2",
      name: "Manta",
      category: "Invierno",
      image: "/images/img1.jpg",
      price: 400,
      brand: "GGC",
      rating: 4.5,
      numReviews: 7,
    },
    {
      _id: "3",
      name: "Pote",
      category: "Invierno",
      image: "/images/img2.jpg",
      price: 220,
      brand: "GGC",
      rating: 4.5,
      numReviews: 7,
    },
    {
      _id: "4",
      name: "Angie",
      category: "Verano",
      image: "/images/img3.jpg",
      price: 550,
      brand: "GGC",
      rating: 4.5,
      numReviews: 4,
    },
    {
      _id: "5",
      name: "SSSSSST FFFFLEUR",
      category: "Verano",
      image: "/images/img4.jpg",
      price: 20,
      brand: "GGC",
      rating: 1.5,
      numReviews: 9,
    },
    {
      _id: "6",
      name: "BUFANDA",
      category: "Verano",
      image: "/images/img5.jpg",
      price: 150,
      brand: "GGC",
      rating: 4.5,
      numReviews: 10,
    },
  ],
};
